### model
model_name_or_path: /root/autodl-tmp/deepseek
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
# lora_target: ["q_proj", "v_proj"]
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: mydata
template: deepseekr1
cutoff_len: 2048
max_samples: 1500
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /root/autodl-tmp/saves/deepseek-r1v3
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-5    
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
